version: '3'

services:
  rtmp-server:
    container_name: rtmp-server
    build: .
    ports:
      - 1935:1935
    restart: always
    networks:
      - web
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.rtmp-server.rule=Host(`example.com`)
      - traefik.http.routers.rtmp-server.entrypoints=web-secure
      - traefik.http.routers.rtmp-server.tls=true
      - traefik.http.routers.rtmp-server.tls.certresolver=le
      - traefik.http.services.rtmp-server.loadbalancer.server.port=80

networks:
  web:
    external: true
